repos:
  # Codespell for common misspellings
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        files: ^.*\.(py|c|h|md|rst|yml)$
  # Ruff for Python formatting and linting
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.9.6
  #   hooks:
  #     # Run the linter.
  #     - id: ruff
  #       types_or: [python, pyi]
  #       args: ["--fix"]
  #       stages: [pre-commit]
  #     # Run the formatter.
  #     - id: ruff-format
  #       types_or: [python, pyi]
  #       stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # the release, git tag, or commit you want to use
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
