[project]
name = "autoreg-metadata"
version = "0.1.0"
description = "Automated registration package for urban sensor endpoints into metadata catalogs"
authors = [
    {name = "Jeffrey Limnardy",email = "jeffreylimnardy@yahoo.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pydantic (>=2.10.4,<3.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "ckanapi (>=4.8,<5.0)",
    "python-dotenv (>=1.0.1)",
    "geojson (>=3.2.0)"
]

[tool.poetry]
packages = [{include = "autoreg_metadata"}]

[tool.poetry.group.test.dependencies]
pytest = "^8.3.0"
pytest-mock = "*"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8.0"
poetry-plugin-shell = ">=1.0.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.optional-dependencies]
teleclass-classifier = [
    "sentence-transformers>=3.3.1",
    "networkx>=3.4.2",
    "numpy>=2.2.1",
    "ollama>=0.4.5",
    "yake>=0.4.8",
    "keybert>=0.8.5",
    "rank_bm25>=0.2.2",
]
